services:
  - type: web
    name: circle-tok
    runtime: node
    repo: https://github.com/AlekseyNaruto/circle-tok
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MODERATOR_ID
        value: 2044125331
      - key: CHANNEL_PENDING
        value: "@CircleTokpending"
      - key: PORT
        value: 3000
